# Generated by Django 5.0.2 on 2024-03-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('credit_unit', models.CharField(max_length=100)),
                ('course_code1', models.CharField(max_length=100)),
                ('course_title1', models.CharField(max_length=100)),
                ('credit_unit1', models.CharField(max_length=100)),
                ('course_code2', models.CharField(max_length=100)),
                ('course_title2', models.CharField(max_length=100)),
                ('credit_unit2', models.CharField(max_length=100)),
                ('course_code3', models.CharField(max_length=100)),
                ('course_title3', models.CharField(max_length=100)),
                ('credit_unit3', models.CharField(max_length=100)),
                ('course_code4', models.CharField(max_length=100)),
                ('course_title4', models.CharField(max_length=100)),
                ('credit_unit4', models.CharField(max_length=100)),
                ('course_code5', models.CharField(max_length=100)),
                ('course_title5', models.CharField(max_length=100)),
                ('credit_unit5', models.CharField(max_length=100)),
                ('course_code6', models.CharField(max_length=100)),
                ('course_title6', models.CharField(max_length=100)),
                ('credit_unit6', models.CharField(max_length=100)),
                ('course_code001', models.CharField(max_length=100)),
                ('course_title001', models.CharField(max_length=100)),
                ('credit_unit001', models.CharField(max_length=100)),
                ('course_code002', models.CharField(max_length=100)),
                ('course_title002', models.CharField(max_length=100)),
                ('credit_unit002', models.CharField(max_length=100)),
                ('course_code003', models.CharField(max_length=100)),
                ('course_title003', models.CharField(max_length=100)),
                ('credit_unit003', models.CharField(max_length=100)),
                ('course_code004', models.CharField(max_length=100)),
                ('course_title004', models.CharField(max_length=100)),
                ('credit_unit004', models.CharField(max_length=100)),
                ('course_code005', models.CharField(max_length=100)),
                ('course_title005', models.CharField(max_length=100)),
                ('credit_unit005', models.CharField(max_length=100)),
                ('course_code006', models.CharField(max_length=100)),
                ('course_title006', models.CharField(max_length=100)),
                ('credit_unit006', models.CharField(max_length=100)),
                ('course_code007', models.CharField(max_length=100)),
                ('course_title007', models.CharField(max_length=100)),
                ('credit_unit007', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
